version: '3'
services:

  mysql:
    image: mysql:latest
    container_name: dev_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "tin-mysql-sequelize"
    volumes:
      - "mysqldata:/var/lib/mysql"

volumes:
  mysqldata: